### ISSUE TITLE
`parser.rs`: consider using `VecDeque` for `stack` in `search_for_attr`

### ISSUE THREAD

**Issue by zseri** [DieracDelta/flake_generator#10]
https://github.com/DieracDelta/flake_generator/blob/d9b002d10600a29ece56e0a9ede003fc3870fdef/src/parser.rs#L148
This code is extremely suboptimal performance-wise. It might be a good idea to use `std::collections::VecDeque` instead of `Vec` for `stack` in `search_for_attr`, and replace `.insert(0, ` with `.push_front(` (and `.push` with `.push_back`)

**Comment by DieracDelta** [comment]
I was trying to BFS, which was the reason for the queue data structure. I realized that this is a source of bugs and switched to DFS. As a result, we only need a stack and not a queue (see #11 ).  Does using `Vec` for stack in this context make sense?

**Comment by zseri** [comment]
yes.
